FROM node:23-alpine3.20

WORKDIR /app
COPY package.json ./
COPY tsconfig.json ./
ARG GH_PAT
ENV GH_PAT=${GH_PAT}
COPY .npmrc .npmrc
COPY src ./src
RUN ls -a
RUN npm install 
RUN npm install -g nodemon

EXPOSE 4005

CMD [ "npm", "run", "dev" ]